config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'

    authenticated :user do
      root to: 'contacts#index', as: 'authenticated_user_root'
    end     
  end

  root 'users/sessions#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    # Save contact
    @contact = Contact.new(contact_params)
    current_user.contacts << @contact
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :url, :phone)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= simple_form_for(@contact) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/contacts/edit.html.haml
.row.heading
  .col-xs-offset-3.col-xs-6
    %h2.form-left-margin Edit Contact
    .contact-form
      = simple_form_for(@contact) do |f|
        = f.error_notification

        .form-inputs
          = f.input :first_name, required: true
          = f.input :last_name
          = f.input :phone
          = f.input :email
          = f.input :url

        .form-actions
          = f.button :submit, :class=>"btn-md btn-success btn-block"
          = link_to 'Go Back', contacts_path, :class=>"btn-md btn-primary btn-block"
  

app/views/contacts/index.html.haml
.row.heading
  .col-xs-6
    %h2 Your Contacts
  .col-xs-6
    = link_to '+', new_contact_path, :class=>"btn btn-primary pull-right add-contact", :data => {:toggle => "tooltip"}, :title=>"Add new contact"
.row   
  - @contacts.each do |contact|
    .col-xs-12.col-md-6.col-lg-6
      .contact-card
        .row
          .col-xs-6.col-md-6
            %label First Name: 
            %p
              = contact.first_name    
        .row
          .col-xs-6.col-md-6
            %label Last Name: 
            %p
              = contact.last_name
        .row
          .col-xs-6.col-md-6
            %label Email: 
            %p
              = contact.email
        .row
          .col-xs-6.col-md-6
            %label Phone: 
            %p
              = contact.phone
        .row
          .col-xs-6.col-md-6
            %label URL: 
            %p
              = contact.url
        .action-buttons
          .row
            .col-xs-12.col-md-12
              = link_to 'Edit Contact', edit_contact_path(contact), :class=>"btn btn-success btn-block"
          .row
            .col-xs-12.col-md-12
              = link_to "Delete Contact", contact_path(contact), method: :delete, :class=>"btn btn-danger btn-block"

app/views/contacts/new.html.haml
.row.heading
  .col-xs-offset-3.col-xs-6
    %h2.form-left-margin New Contact
    .contact-form
      = simple_form_for(@contact) do |f|
        = f.error_notification
        .form-inputs
          = f.input :first_name, required: true, :placeholder=>"Enter first name"
          = f.input :last_name, :placeholder=>"Enter last name"
          = f.input :email, :placeholder=>"Enter valid email"
          = f.input :phone, :placeholder=>"Enter valid phone number"
          = f.input :url, :placeholder=>"Enter your contact's url"

        .form-actions
          = f.button :submit, :class=>"btn-md btn-success btn-block"
          = link_to 'Back', contacts_path, :class=>"btn-md btn-primary btn-block"

app/views/contacts/show.html.haml
.row.heading
  %p#notice.alert.alert-success
    = notice

  .show-buttons
  .row
    .col-xs-offset-3.col-xs-6
      = link_to 'Edit Contact', edit_contact_path(@contact), :class=>"btn btn-success btn-block"
      = link_to 'Back to Contacts', contacts_path, :class=>"btn btn-primary btn-block"